name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clone Submodules
      run: git submodule update --init --recursive

    - name: Build Module
      id: build
      run: |
        make
        echo "::set-output name=status::success"
        echo "::set-output name=modulePath::akashaProxy-$(git rev-parse --short HEAD).zip"

    - name: Upload Artefact
      uses: actions/upload-artifact@main
      if: steps.build.outputs.status == 'success' && !cancelled()
      with:
        name: module
        path: ${{ steps.build.outputs.modulePath }}
